//go:build js

package web

import "github.com/michaelraines/future-core/internal/platform"

// keyCodeMap maps DOM KeyboardEvent.code strings to platform.Key.
var keyCodeMap = map[string]platform.Key{
	"Space":        platform.KeySpace,
	"Quote":        platform.KeyApostrophe,
	"Comma":        platform.KeyComma,
	"Minus":        platform.KeyMinus,
	"Period":       platform.KeyPeriod,
	"Slash":        platform.KeySlash,
	"Digit0":       platform.Key0,
	"Digit1":       platform.Key1,
	"Digit2":       platform.Key2,
	"Digit3":       platform.Key3,
	"Digit4":       platform.Key4,
	"Digit5":       platform.Key5,
	"Digit6":       platform.Key6,
	"Digit7":       platform.Key7,
	"Digit8":       platform.Key8,
	"Digit9":       platform.Key9,
	"Semicolon":    platform.KeySemicolon,
	"Equal":        platform.KeyEqual,
	"KeyA":         platform.KeyA,
	"KeyB":         platform.KeyB,
	"KeyC":         platform.KeyC,
	"KeyD":         platform.KeyD,
	"KeyE":         platform.KeyE,
	"KeyF":         platform.KeyF,
	"KeyG":         platform.KeyG,
	"KeyH":         platform.KeyH,
	"KeyI":         platform.KeyI,
	"KeyJ":         platform.KeyJ,
	"KeyK":         platform.KeyK,
	"KeyL":         platform.KeyL,
	"KeyM":         platform.KeyM,
	"KeyN":         platform.KeyN,
	"KeyO":         platform.KeyO,
	"KeyP":         platform.KeyP,
	"KeyQ":         platform.KeyQ,
	"KeyR":         platform.KeyR,
	"KeyS":         platform.KeyS,
	"KeyT":         platform.KeyT,
	"KeyU":         platform.KeyU,
	"KeyV":         platform.KeyV,
	"KeyW":         platform.KeyW,
	"KeyX":         platform.KeyX,
	"KeyY":         platform.KeyY,
	"KeyZ":         platform.KeyZ,
	"BracketLeft":  platform.KeyLeftBracket,
	"Backslash":    platform.KeyBackslash,
	"BracketRight": platform.KeyRightBracket,
	"Backquote":    platform.KeyGraveAccent,
	"Escape":       platform.KeyEscape,
	"Enter":        platform.KeyEnter,
	"Tab":          platform.KeyTab,
	"Backspace":    platform.KeyBackspace,
	"Insert":       platform.KeyInsert,
	"Delete":       platform.KeyDelete,
	"ArrowRight":   platform.KeyRight,
	"ArrowLeft":    platform.KeyLeft,
	"ArrowDown":    platform.KeyDown,
	"ArrowUp":      platform.KeyUp,
	"PageUp":       platform.KeyPageUp,
	"PageDown":     platform.KeyPageDown,
	"Home":         platform.KeyHome,
	"End":          platform.KeyEnd,
	"CapsLock":     platform.KeyCapsLock,
	"ScrollLock":   platform.KeyScrollLock,
	"NumLock":      platform.KeyNumLock,
	"PrintScreen":  platform.KeyPrintScreen,
	"Pause":        platform.KeyPause,
	"F1":           platform.KeyF1,
	"F2":           platform.KeyF2,
	"F3":           platform.KeyF3,
	"F4":           platform.KeyF4,
	"F5":           platform.KeyF5,
	"F6":           platform.KeyF6,
	"F7":           platform.KeyF7,
	"F8":           platform.KeyF8,
	"F9":           platform.KeyF9,
	"F10":          platform.KeyF10,
	"F11":          platform.KeyF11,
	"F12":          platform.KeyF12,
	"F13":          platform.KeyF13,
	"F14":          platform.KeyF14,
	"F15":          platform.KeyF15,
	"F16":          platform.KeyF16,
	"F17":          platform.KeyF17,
	"F18":          platform.KeyF18,
	"F19":          platform.KeyF19,
	"F20":          platform.KeyF20,
	"F21":          platform.KeyF21,
	"F22":          platform.KeyF22,
	"F23":          platform.KeyF23,
	"F24":          platform.KeyF24,
	"ShiftLeft":    platform.KeyLeftShift,
	"ShiftRight":   platform.KeyRightShift,
	"ControlLeft":  platform.KeyLeftControl,
	"ControlRight": platform.KeyRightControl,
	"AltLeft":      platform.KeyLeftAlt,
	"AltRight":     platform.KeyRightAlt,
	"MetaLeft":     platform.KeyLeftSuper,
	"MetaRight":    platform.KeyRightSuper,
}

// mapKeyCode converts a DOM KeyboardEvent.code to a platform.Key.
// Returns -1 for unmapped keys.
func mapKeyCode(code string) platform.Key {
	if k, ok := keyCodeMap[code]; ok {
		return k
	}
	return -1
}
